### ISSUE TITLE
[Feature request] Whitelist mode

### ISSUE THREAD

**Issue by KaKi87** [KieronQuinn/DarQ#10]
Hello,

The app currently works in blacklist mode : unchecked apps are untouched by default and checked apps are dark-forced.

I'd like to be able to choose to work in whitelist mode : unchecked apps are dark-forced by default and checked apps are untouched.

Because, after all, DarQ's purpose is to allow the user to exclude apps while (1) they're natively dark, or (2) they're looking bad when dark-forced.

Thanks

**Comment by KieronQuinn** [comment]
Assuming you want a blacklist, the app already has a whitelist (which doesn't refer to the colours of the apps)

This has been asked for many times and is not feasible. I explained why [here](https://forum.xda-developers.com/showpost.php?p=81696799&postcount=177), as well as in many other places in the thread.

**Comment by KaKi87** [comment]
> Assuming you want a blacklist, the app already has a whitelist

Yes, I confused the terms, sorry.

> This [...] is not feasible. I explained why [here](https://forum.xda-developers.com/showpost.php?p=81696799&postcount=177)

> A "blacklist" isn't something I want to implement as it would cause the default to be force-dark enabled, which would inevitably cause people to complain to developers that it doesn't look right, which wouldn't be a good thing. It would also mean you'd have to have the inverted status bar all the time, and apps would randomly look incorrect. Quite simply, you don't actually want this.

According to your answer from XDA, *not feasible* is not the appropriate term : you're just worried that some people will not understand how the app works.

I understand that, however, I'm not asking you to change the app's default behavior : actually, I'm asking you to have it as an optional feature that users could enable manually, and with a warning, if you think it's necessary.

Thanks

**Comment by KaKi87** [comment]
> you'd be far more prone to force dark not being disabled in time when an app launches

I'm sorry I don't understand that part of your sentence ?

**Comment by KieronQuinn** [comment]
DarQ doesn't always work in time. You know those apps that don't go into force dark when you have them on with the whitelist (they stay light), but that work when you have force dark enabled globally or in the system settings? That's why.

If an app doesn't go dark in time, it's not the end of the world, they're still usable. If an app doesn't go light in time and doesn't work properly with force dark, they can be unusable. And the only way that you could fix that if there were a blacklist would be to disable DarQ entirely. I don't want that. 

This won't change, it's not happening.

**Comment by KaKi87** [comment]
> DarQ doesn't always work in time.

Oh, yes, I experienced that issue sometimes. However, disabling background energy battery optimization for DarQ fixed it.

> If an app doesn't go light in time and doesn't work properly with force dark, they can be unusable.

Do you mean that DarQ is actually switching the system-wide setting everytime the user switches between dark-forced and untouched apps ??

**Comment by KieronQuinn** [comment]
> > DarQ doesn't always work in time.
> 
> Oh, yes, I experienced that issue sometimes. However, disabling background energy battery optimization for DarQ fixed it.

Not for everyone. Implementing it for just some would not be a fair nor good idea. 

> 
> > If an app doesn't go light in time and doesn't work properly with force dark, they can be unusable.
> 
> Do you mean that DarQ is actually switching the system-wide setting everytime the user switches between dark-forced and untouched apps ??

Yes, that's exactly what DarQ does, and it doesn't try to hide that. You can see it in the code too, all it's doing deep down is setting the system property `persist.hwui.force_dark` depending on which app has launched.

**Comment by KaKi87** [comment]
> Implementing it for just some would not be a fair nor good idea.

Well, for example, VLC's support for High Efficiency Video Coding (HEVC), i.e. the most powerful video compression codec, requires minimal GPU performances, and whether you have a low-cost phone, or a low-cost PC, it will crash. Yet, the feature is available for everyone.

**Comment by KieronQuinn** [comment]
HEVC doesn't cause other apps to be unusable for those it doesn't work on though does it.

Anyway, this isn't going to change. If you want to add it, fork the project and add it yourself. End of discussion.
