### ISSUE TITLE
[Bug] DarQ visible in apps list

### ISSUE THREAD

**Issue by KaKi87** [KieronQuinn/DarQ#11]
Hello,

While checking all apps in the list, I accidentally checked DarQ too, so it crashed.

Since it's happening to all apps when checking them, I suppose it's a mandatory step and there's nothing we can do about it, right ?

However, DarQ should be hidden from the list, so that it cannot happen to itself.

Besides, DarQ didn't only crashed but also reset itself.

Thanks

**Comment by KieronQuinn** [comment]
Good point, I'll fix this in the next version

Thanks

**Comment by KieronQuinn** [comment]
Fixed in 1.3
