### ISSUE TITLE
Requires reboot

### ISSUE THREAD

**Issue by Shacklebolt13** [KieronQuinn/DarQ#12]
Hi, I am using Redmi 4x santoni, on MIUI 11 and am rooted.  Theres an error stating "Force dark requires the system dark theme to be enabled to work. Please enable it below to see changes in apps".
Dark mode requires restart, which is quite inconvenient. Isn't there any solutions to this problem?
I am rooted, so can't i smh enable the dark mode?
 Other apps like dark mode report that devs have disabled this feature. Any way to Enable?

**Comment by KieronQuinn** [comment]
Dark mode does not require a restart on any other device I've ever come across. If it does on your device, there's nothing I can do about that.

And no, you can't enable force dark on apps that specifically disable it.
