### ISSUE TITLE
'Force Dark Theme' option turning off after each reboot

### ISSUE THREAD

**Issue by TheGreySquare** [KieronQuinn/DarQ#13]
Android 10, AOSP

**Comment by KieronQuinn** [comment]
This wasn't actually an intended feature, the force dark theme toggle just changes the system setting, but a few have asked for it to persist so I'll add it in the future

**Comment by TheGreySquare** [comment]
> This wasn't actually an intended feature, the force dark theme toggle just changes the system setting, but a few have asked for it to persist so I'll add it in the future

Thank you, appreciate it

**Comment by KieronQuinn** [comment]
Done in 1.3
