### ISSUE TITLE
Darq applies dark mode to SwiftKey despite not being enabled. 

### ISSUE THREAD

**Issue by heatl0rd** [KieronQuinn/DarQ#14]
I noticed my dark keyboards were being lit up white when darq was enabled. I went into my enabled list to check if I accidently enabled it, which I didn't.

Please advise on how I can assist to troubleshoot this.

**Comment by KieronQuinn** [comment]
This can't be resolved, keyboards don't work like apps in the view of the Accessibility Service stuff, and even if they did it would end up out of sync as the keyboard isn't reloaded between different apps
