### ISSUE TITLE
[Feature request] Use accessibility color invert feature for undarkifyable apps

### ISSUE THREAD

**Issue by KaKi87** [KieronQuinn/DarQ#15]
Hello,

I'd like to suggest allowing the user to choose using the color invert feature available in Android accessibility settings for specific apps when the smart dark mode doesn't work.

Thanks

**Comment by KieronQuinn** [comment]
As colour inversion breaks images (and force dark is basically just an implementation of inversion that spares images), I won't be doing this. It just breaks apps.

**Comment by KaKi87** [comment]
Well, force dark does break images on Amazon and Tinder anyway.

**Comment by KaKi87** [comment]
And also in webview.

**Comment by KieronQuinn** [comment]
That's because it's meant as a developer option to implement with exclusions, the force option is to allow easy checking of what works and what doesn't. It breaking some apps is exactly the point of this app.

**Comment by KaKi87** [comment]
Yes, so what's wrong with adding color invert as a fallback option ?
