### ISSUE TITLE
snapchat

### ISSUE THREAD

**Issue by G4TH3RR** [KieronQuinn/DarQ#16]
Dark mode on snapchat no longer works.

**Comment by Khalufa** [comment]
Hi adminstore @snapchat we have broplem when 
log out & sing in 

3 or 5 peson like that problem

**Comment by KieronQuinn** [comment]
This is Snapchat's problem, not DarQ's. The Xposed module in 1.3 will work with Snapchat, at the risk of being banned if they detect Xposed.
