### ISSUE TITLE
[problem] after updating from 1.1 to 1.3

### ISSUE THREAD

**Issue by Bradford1040** [KieronQuinn/DarQ#19]
I created a few posts on xda, I am on version 1.3 & had updated from 1.1. I have a Samsung A50 A10 one ui 2.0, use nova launcher & Klwp & tasker. All permissions have been given, I have done a fresh install, wiped cache & data, restarted. Everything I have read or knew of, I have done.

The app is working, but it isn't, I can not change any settings as the app is stuck at "connection to services" but as I have said it's still working, apps that I had forced via 1.1 are still in dark mode (after I run adb Wifi cmd). The big one for me is Amazon shopping app, because of late night window shopping lol.

Is there anything I can do to fix the problem? Or something I did that is causing it?

Apologies for posting in the wrong github, somehow my wires got crossed, and I posted in tap tap

Edit:
Been about a month, I am not bitchin or complaining, I am just wondering if at the very least I can get a link to version 1.1 apk? Or is it right in front of me and I don't see it?

**Comment by KieronQuinn** [comment]
You can find the old versions here: https://www.apkmirror.com/apk/mighty-quinn-apps/darq/

As for the bug, I can't really do much about it without having access to the device. Service connection using the root services concept can be buggy on some devices, and very hard to debug if it can't be reproduced. Could you try 1.2 as well, see if it's new in 1.3 or also in that version?

**Comment by Bradford1040** [comment]
Thank you, I think I was confused on the version I was using BTW,

I am not rooted, so 1.2 seems to be the version that works for me. But you
can close the report, as 1.2 fixed the issue I was having.

Thank you for the link, time, and a great app!

Bradford Adams
