### ISSUE TITLE
Script is incompatible with zsh shell

### ISSUE THREAD

**Issue by justin-hackin** [KieronQuinn/DarQ#20]
```
sh rundarq-linux-mac.sh
rundarq-linux-mac.sh: 3: Syntax error: "(" unexpected
```

when using zsh as shell. 

```
bash rundarq-linux-mac.sh
```

works as expected.  Seasoned hackers should quickly figure this out but might be nice to update the readme.

**Comment by KieronQuinn** [comment]
v2.0 no longer uses the script, so I'm closing this
