### ISSUE TITLE
Unable to find adb

### ISSUE THREAD

**Issue by izchieve** [KieronQuinn/DarQ#21]
- So I've updated my adb driver and I checked the command prompt for "adb devices" and it says the the daemon connected successfully in which my device has been attached. I've activated the accessibility service for DarQ, but when I run the script, it still says **"Unable to find adb. Please make sure you extracted the full zip file including the tools folder containing adb.exe before running this script."** The tools folder is there and the adb.exe also is there, so I'm not sure where I went wrong even though I've followed all the steps.

**Comment by KieronQuinn** [comment]
v2.0 no longer relies on the ADB script, so this shouldn't be an issue. You may have to install ADB via one of the other more standard methods though.
