### ISSUE TITLE
Please remove the glaring white splash screen!

### ISSUE THREAD

**Issue by iamMG** [KieronQuinn/DarQ#22]
I have dark system theme on my OP 7 Pro. All my apps have dark theme natively enabled or through DarQ. And I am thankful for this app for that. 
However, sometimes when I open DarQ, it takes a while to load up and start the service. During this time a glaring white splash screen comes up, which is only aesthetic, completely unnecessary and doesn't add any value to the app. So I request you to remove it or replace it with something else. Please!
![Screenshot_20201215-155144](https://user-images.githubusercontent.com/22472867/102203086-25aa7a00-3eee-11eb-90b0-c230778bb850.png)

**Comment by KieronQuinn** [comment]
You'll be pleased to know this didn't survive the rewrite.
