### ISSUE TITLE
Usable screen space in the app is cut in half

### ISSUE THREAD

**Issue by erayrafet** [KieronQuinn/DarQ#26]
The screen space usable throughout the app appears cut in half with v1.3 on My POCOPHONE F1 running Pixel Experience Android 11. Happens immediately after invoking the virtual keyboard in the search page and persists until killing the app and reopening it.

![Screenshot_20210113-154422.png](https://user-images.githubusercontent.com/34194191/104460326-a1afe480-55b6-11eb-8833-cd0e853b8115.png)![Screenshot_20210113-154411.png](https://user-images.githubusercontent.com/34194191/104460329-a4123e80-55b6-11eb-8802-73c587106fcb.png)
![Screenshot_20210113-154802.png](https://user-images.githubusercontent.com/34194191/104460413-bee4b300-55b6-11eb-878d-1bbf89e304d3.png)
You can see clearly from the scrollbar track.

**Comment by erayrafet** [comment]
The issue persists with or without my Substratum theme applied.

**Comment by KieronQuinn** [comment]
Should be fixed in 2.0
