### ISSUE TITLE
Service not running after magisk update? 

### ISSUE THREAD

**Issue by MrHappy** [KieronQuinn/DarQ#27]
Darq used to work.
Now when I start it, it says 'service not running'.
My phone has A10, is rooted and has Magisk 21.3 and EdXposed 0.5.1.4.
Also check xda thread [XDA Thread](https://forum.xda-developers.com/t/app-root-adb-10-11-oct-darq-per-app-selectable-force-dark-option-for-android-10.3944356/post-84300223)

**Comment by ErdbeerbaerLP** [comment]
I am having the same problem
(magisk 21.3, Android 10, Edxposed 0.5.1.4, Samsung galaxy A70)

**Comment by ToonHermans** [comment]
Same problem on Android 11.

**Comment by rexcelsior** [comment]
Same problem. AOSP Android 10 with Magisk Beta.

**Comment by oliver802** [comment]
Same on magisk 21.3 Android 11

**Comment by oliver802** [comment]
And Exposed 0.5.1.4

**Comment by znbaboy** [comment]
Sams here. Magisk 21.3 Android 10. 

Had to downgrade to Magisk 21.2 to get it working again

**Comment by MrHappy** [comment]
Was a magisk issue, most recent update fixed it.
