### ISSUE TITLE
Apps no longer supported

### ISSUE THREAD

**Issue by Kreuger** [KieronQuinn/DarQ#28]
Hey man. Ive started to notice recently that some apps wont adhere to the dark mode but they used to before. One of them that I used today is AliExpress. I cant think of the other one I saw off the top of my head. But anyways Im on Lineage OS (10) with root.

**Comment by Kreuger** [comment]
Oops I had a setting wrong.

**Comment by Kreuger** [comment]
Reopening because AliExpress still doesnt work for me. But its currently the only app causing issues.

**Comment by KieronQuinn** [comment]
Please read the FAQ, apps are able to disable force dark. The 2.0 update may improve this, if the app has simply optimised its startup, but if it's still not working, there's nothing I can do. The Xposed module may help you, but again I cannot make guarantees.

**Comment by Kreuger** [comment]
It didnt help but thanks anyways. I have no desire to use xposed again.
