### ISSUE TITLE
DarQ 1.3 unable to connect to Accessibility Service after updating to Magisk 21.4

### ISSUE THREAD

**Issue by ghost** [KieronQuinn/DarQ#29]
DarQ 1.3 always shows "Accessibility Service not running" after updating to Magisk 21.4.
Disabling and re-enabling it does not help. Rebooting the device does not help.

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment]
Here is a log file:
[2021-01-27-15-19-20.txt](https://github.com/KieronQuinn/DarQ/files/5880808/2021-01-27-15-19-20.txt)

**Comment by pvtpeter** [comment]
Situation is the same in Magisk 22.0
@ghost: did you find any solution?

**Comment by KieronQuinn** [comment]
Should be fixed in 2.0
