### ISSUE TITLE
versionCode not increased with 2.0

### ISSUE THREAD

**Issue by IzzySoft** [KieronQuinn/DarQ#34]
Looks like you forgot to increase versionCode: v2.0 has the same (13) v1.3 already came with, so this won't be offered as update (Android considers the two the same). You might wish to fix that and replace the APK at the release.

**Comment by KieronQuinn** [comment]
Oops, my bad. I'll update it with the next update which should be super minor (just messing with Snapchat w/ Xposed), unless a potential issue with Shizuku on Android 12 turns into something bigger.

**Comment by IzzySoft** [comment]
Thanks, that should be fine then. Just let me know here if I should cross-check once the APK was released.

**Comment by pythonboy344** [comment]
Can't see monet option in 2.0 update

**Comment by KieronQuinn** [comment]
> Can't see monet option in 2.0 update

The option to pick from the colors is only available in the developer options, triple tap the about option to enable them. Other than that, there's no option, it's automatic.

**Comment by KieronQuinn** [comment]
Version code in 2.1 is now 21 :)

**Comment by IzzySoft** [comment]
Thanks @KieronQuinn – I can confirm: my updater did not complain but fetched it fine, including the Fastlane updates. Will show up with the next sync tomorrow then :smiley:
