### ISSUE TITLE
Response since you locked the thread

### ISSUE THREAD

**Issue by bgiesing** [KieronQuinn/DarQ#38]
> As I've stated many times in the XDA thread, this won't happen. Force dark is intended to be a developer option, and it regularly breaks apps. With a whitelist, you must consciously choose to pick which apps are themed, and will know to turn them off. With a blacklist, this is not the case.

Except you already have an option in app to force all apps as dark ignoring the whitelist so how is this any different than that? You already allow everyone to unconsciously set all apps dark so there's no point blocking people from selectively unbreaking the apps?? That logic would make sense IF you didn't already allow it as an option

> The enable/disable code is also not immediate when an app launches, so a blacklist would lead to instances of apps being incorrectly force dark when they shouldn't be, rather than the much safer case where they're not themed with the whitelist.

And again, they already are with the option you already added?? If the app already allows you to enable all by default, it throws the entire point of "I don't want to add it so people don't break everything" out the window, why even add that option in the first place if you cared about breakage?

Also just saying, it's kinda rude to not even allow someone to reply immediately locking a topic. You can close the issue without preventing people from responding.

_Originally posted by @KieronQuinn in https://github.com/KieronQuinn/DarQ/issues/36#issuecomment-877455884_

**Comment by KieronQuinn** [comment]
> Except you already have an option in app to force all apps as dark ignoring the whitelist so how is this any different than that? You already allow everyone to unconsciously set all apps dark so there's no point blocking people from selectively unbreaking the apps?? That logic would make sense IF you didn't already allow it as an option

The advanced option does the same as the one in developer options, but survives a reboot. Again, this has been covered many times in the XDA thread, you are not the first one to come up with this idea. It leads to arguments 100% of the time, which is why I now just reply with the same message and drop/lock the subject, as I will do again now.
