### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [KieronQuinn/DarQ#4]
I'd like to see this app available on [F-Droid](https://f-droid.org) store, that's why I've just go ahead and open a request [here](https://gitlab.com/fdroid/rfp/issues/1139). Don't you mind?

**Comment by IzzySoft** [comment]
And would you mind to [tag your releases](https://github.com/KieronQuinn/DarQ/releases) so F-Droid knows which commits to build? Another thing nice to have would be [Fastlane file structure](https://gitlab.com/snippets/1895688) with description, screenshots etc …

**Comment by KieronQuinn** [comment]
I'll look into it

**Comment by IzzySoft** [comment]
Great, thanks! I see you just started tagging. If you could attach the APK as well, I could already serve that via [my repo](https://apt.izzysoft.de/fdroid) until you're ready for "the big one".

**Comment by KieronQuinn** [comment]
Attached the APK too

**Comment by IzzySoft** [comment]
Thanks! Just added it to my repo ([find it here](https://apt.izzysoft.de/fdroid/index/apk/com.kieronquinn.app.darq)); updates will be picked within 24h from your attaching the APK to a new tag.

GMS will be a show-stopper for f-droid.org, though.

PS: you don't plan to open-source AutoMagisk as well?

**Comment by KieronQuinn** [comment]
AutoMagisk is long since dead, I don't plan on even looking at it ever again if I'm honest. 

Thanks for your help

**Comment by IzzySoft** [comment]
Ah, OK – I just saw it at XDA and thought it sounds interesting… Thanks for letting me know. And always glad to help! :smiley:

**Comment by IzzySoft** [comment]
Any chance with Fastlane, @KieronQuinn?
