### ISSUE TITLE
Not amoled, only dark?

### ISSUE THREAD

**Issue by sfksuperman** [KieronQuinn/DarQ#41]
I have enabled Google Rewards app but it's not purely amoled. Is it okay?

Also, during surveys, the option bar remains dark, invisible. The selection points should be white so that we can know which option we have selected.
I don't have the screenshot right now.

**Comment by KieronQuinn** [comment]
Please read the FAQ, there is no control over the colour and the status bar can only be fixed with the included Xposed module.
