### ISSUE TITLE
Keeping (USB debug & Wireless debug) on is necessary? <Samsung OneUI3.1>

### ISSUE THREAD

**Issue by 2ndBillGates** [KieronQuinn/DarQ#42]
I updated to the newest version v.2.1. Noticed that has changed from adb to Shizuku.
Before that, I only need to adb once, Darq will run in the background. 

In this build, needs Shizuku to run in the background all the time, if I disable USB debug, it will not work after settings.

Does keep USB debug continuously on, will leave safety concern?

Thank you

**Comment by KieronQuinn** [comment]
I believe USB debugging has _always_ been required to be on all the time, I thought adbd was killed when you turned it off (which would kill the service pre-Shizuku too)

Yes, if Shizuku requires it DarQ does too. If you prefer (and have the option), use wireless debugging as it would be harder to hijack. However, if you're worried about USB debugging allowing anyone to just plug in your phone and use ADB, that's not the case - there's a permission prompt that you have to unlock the phone for first to allow.
