### ISSUE TITLE
Snapchat Dark Mode not working

### ISSUE THREAD

**Issue by QuestionLife** [KieronQuinn/DarQ#43]
Got this to use specifically for Snapchat (latest version at time of issue [9/23/2021]) and it seems to be the only app on my phone that DarQ does not convert to dark mode. Since Snapchat does not have a built in dark mode as of now for android, I was really looking forward for this app to be the one thing that worked without rooting my phone (AT&T Samsung Galaxy S9 Plus).

I think this is something on Snapchat's end that is preventing it, but i am hoping it is not and is something that you can look into and possibly fix.

Besides that, the app works flawlessly, and the instructions were very clear and easy to follow, props to all of you.

**Comment by KieronQuinn** [comment]
Snapchat requires the Xposed module, this is not a bug.
