### ISSUE TITLE
App request root even after granting.

### ISSUE THREAD

**Issue by UrSok** [KieronQuinn/DarQ#5]
I'm on Havoc 3.0 on Q. Magisk 20.1. I've granted the app root but it doesn't detect it. I've checked in Magisk Manager and yes it has root. I tried to reboot, same problem.

**Comment by Kumaranseruthur** [comment]
No Root Detected

**Comment by KaKi87** [comment]
Hey there, I'm experiencing the exact same issue on the same device with the same OS.
Please @KieronQuinn :)
Thanks !

**Comment by KieronQuinn** [comment]
Fixed in 1.2
