### ISSUE TITLE
Could change App startup white splash screen?

### ISSUE THREAD

**Issue by 921j** [KieronQuinn/DarQ#50]
Thank you so much for such an effective tool!
As we all know, some apps’ cold startup activitys have very disgusting ad splash screens, 
so I used some other tools to replace the startup splash activity of these Apps as It's main activity, but a white splash screen appeared when it started. This looks very dazzling in the dark theme. Can your DarQ convert These white screens have turned dark, thanks again!

**Comment by KieronQuinn** [comment]
It already should. Depending on the app it might not be applied quick enough however, but what it's doing currently is the best it can do.
