### ISSUE TITLE
DarQ have non free dependencies

### ISSUE THREAD

**Issue by NSTAdventure** [KieronQuinn/DarQ#53]
what is it and why?

**Comment by KieronQuinn** [comment]
Which one? All of them are labelled in here

https://github.com/KieronQuinn/DarQ/blob/master/app/build.gradle

**Comment by NSTAdventure** [comment]
> Which one? All of them are labelled in here
> 
> https://github.com/KieronQuinn/DarQ/blob/master/app/build.gradle

idk
and funny thing is f droid actually report this from long time ago but idk what the heck happenning with me I didn't realize it at all

**Comment by KieronQuinn** [comment]
I don't control the F-Droid page.

**Comment by gnuhead-chieb** [comment]
due to gms

**Comment by KieronQuinn** [comment]
> due to gms

The only GMS dependency is the OSS libraries one which exists solely to list dependencies. I will not be changing that.

**Comment by gnuhead-chieb** [comment]
Yeah, it using only using OSS Licenses Plugin and it completely [opensource](https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin) and does not connect Google's server anymore.
so it anti-feature is obviously mistake.it should report to izzy's repo issue tracker.

**Comment by gnuhead-chieb** [comment]
@IzzySoft

**Comment by IzzySoft** [comment]
Have you checked its dependencies? While the plugin itself ships under the flag of a free license, it drags in GMS (guess why it's called `play-services-oss-licenses` and what the `play-services-` prefix stands for), which is non-free. Nothing I can do about that – apart from [pointing you here](https://gitlab.com/-/snippets/1896503#license-dialogs).

So for my repo (where it currently resides) it means the `NonFreeDep` anti-feature (s it depends on non-free GMS) – for F-Droid.org it would even be a show-stopper.

**Comment by gnuhead-chieb** [comment]
Oh yeah,there is com.google.android.gms.auth and  com.google.android.gms.common also there.
you are right.I missed these.

**Comment by IzzySoft** [comment]
Happens to the best of us :smile:

**Comment by IzzySoft** [comment]
@KieronQuinn as it proved valid, mind to reopen and fix? The [F-Droid inclusion request](https://gitlab.com/fdroid/rfp/-/issues/1139) is stalled because of this. Possible solutions, as already linked before, can be [found here](https://gitlab.com/-/snippets/1896503#license-dialogs). Thanks!

**Comment by KieronQuinn** [comment]
> > due to gms
> 
> The only GMS dependency is the OSS libraries one which exists solely to list dependencies. I will not be changing that.

This remains unchanged, I do not plan to change OSS library.

**Comment by IzzySoft** [comment]
Sad. So in order to display FOSS dependencies, a proprietary library must be used as only show-stopper to having your app fully FOSS. Well, we'll have to accept that then – and unfortunately must close the inclusion request unprocessed. Thanks for your response nevertheless, and the best for your project! Should you one day change your mind, we'll welcome your app!
