### ISSUE TITLE
Not working for any apps

### ISSUE THREAD

**Issue by 916-Serban-Cristian** [KieronQuinn/DarQ#55]
I've just installed Shizuku and DarQ 2.2.1 on my non-rooted Galaxy Note9 running Android 10 but it doesn't work on any app at all. I don't know what logs or screenshots I should provide for further troubleshooting. Shizuku reports as running on 12.6 from adb and DarQ is authorised. DarQ doesn't work in any app even when I toggle the advanced option to always use force dark.

**Comment by KieronQuinn** [comment]
Please read the FAQs. Specifically [this one](https://github.com/KieronQuinn/DarQ/blob/master/app/src/main/assets/faq.md#force-dark-doesnt-work-at-all-on-an-app-can-you-fix-it). Force Dark not working on an app is not a bug. You can try using the Xposed module but no guarantees it will work.
