### ISSUE TITLE
What happpend to adb script

### ISSUE THREAD

**Issue by Golde2341** [KieronQuinn/DarQ#56]
I cant root my deivce so i decided to use the adb script but the zip just dissapear from the xda thread
![image](https://user-images.githubusercontent.com/85361118/158097709-f9980ecb-3acf-44fc-a382-93631af682fb.png)

**Comment by KieronQuinn** [comment]
The ADB script is no longer required as of version 2.0. If you still need it as you are using an older version (which you shouldn't be), scroll down in the releases to the last version before 2.0 and it's there.
