### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by BuffaloDebile** [KieronQuinn/DarQ#57]
Hi, 
I have a phone that is not rooted and Android 11.

Developer mode is activated with USB debugging; everytime I run the file I get this error message :

_"Unable to find adb. Please make sure you extracted the full zip file including the tools folder containing adb.exe
before running this script._"

Any Idea why?

**Comment by KieronQuinn** [comment]
The ADB script is no longer needed, please use a newer version of the app and Shizuku.
