### ISSUE TITLE
Doesn't work for tiktok

### ISSUE THREAD

**Issue by Tobim6** [KieronQuinn/DarQ#58]
It doesn't work for tiktok and that was the only main thing why I wanted it. 

How to fix?

**Comment by KieronQuinn** [comment]
DarQ does not target specific apps and cannot be fixed for them. Try using the Xposed module, if that doesn't work then nothing can be done.

**Comment by Tobim6** [comment]
How can I install the xposed module? Can it brick my device
-původní zpráva-
Předmět: Re: [KieronQuinn/DarQ] Doesn't work for tiktok (Issue #58)
Od: Kieron Quinn ***@***.***>
Datum: 02.04.2022 01:55

DarQ does not target specific apps and cannot be fixed for them. Try using the Xposed module, if that doesn't work then nothing can be done.

**Comment by KieronQuinn** [comment]
The module is built into the app, simply enable it in the Xposed manager for any apps that you want to try to make dark.

**Comment by noxio90** [comment]
> The module is built into the app, simply enable it in the Xposed manager for any apps that you want to try to make dark. 

where can i enable it? do i need an app?

**Comment by KieronQuinn** [comment]
> > The module is built into the app, simply enable it in the Xposed manager for any apps that you want to try to make dark.
> 
> where can i enable it? do i need an app?

The reply you quoted tells you. It's an Xposed module. You need Xposed.
