### ISSUE TITLE
Monet Themes Throwing Error

### ISSUE THREAD

**Issue by alexhulbert** [KieronQuinn/DarQ#60]
Hi, when I tap the "Monet Color Picker" button, I get a pop up that reads "Monet Color Picker unavailable for the currently selected wallpaper." This happens regardless of whether I use a static or dynamic wallpaper and there are no relevant logs in the output of adb logcat. Also, the ROM I'm running (Paranoid Android Sapphire) is super close to stock Android.

Is there anything I can do to get more info about this issue?

Thanks!

**Comment by KieronQuinn** [comment]
Which Android version?

**Comment by alexhulbert** [comment]
I'm on Android 12

**Comment by KieronQuinn** [comment]
That's intentional, you must configure the colours in the system settings.
