### ISSUE TITLE
Service timeout if magiskhide is enabled

### ISSUE THREAD

**Issue by ShojiVR** [KieronQuinn/DarQ#61]
My banking apps requires me to use magisk hide so it can be launched on root.

The problem is once i enable magisk hide, the DarQ itself will not working, it only works if i turn off the magisk hide.

Any solution?

**Comment by KieronQuinn** [comment]
You should not enable Magisk Hide on DarQ, unless you're using the Shizuku method as that will continue to work without root access. This is normal behaviour.
