### ISSUE TITLE
Can't use shadow or border in MX Player Subtitle 

### ISSUE THREAD

**Issue by MohamadBayz** [KieronQuinn/DarQ#63]
The problem is when i use them it is a white outline of a white text so that make it unreadable and trying to change the color doesn't change a thing because black turned to white and white is still white so there's no black border for the text or even a little dark color

**Comment by KieronQuinn** [comment]
The actual implementation is not controlled by DarQ, this is not a problem I can solve. [Please read the FAQs](https://github.com/KieronQuinn/DarQ/blob/master/app/src/main/assets/faq.md#force-dark-makes-an-app-look-weird-can-you-fix-it).
