### ISSUE TITLE
建议反馈

### ISSUE THREAD

**Issue by k650dg4d2** [KieronQuinn/DarQ#66]
阿里巴巴的闲鱼没有完全生效com.taobao.idlefish（https://apkpure.com/cn/%E9%97%B2%E9%B1%BC/com.taobao.idlefish ），
有一些APP自身有深色模式，但是并不会随着手机深色模式打开而打开，需要用户自己打开设置页面自己开启。可以在darq强制深色模式的时候调用这个APP自带的深色模式吗。比如百度网盘（com.baidu.netdisk）和soul（[cn.soulapp.android](https://apkpure.com/cn/soul-%E5%B9%B4%E8%BD%BB%E4%BA%BA%E7%9A%84%E7%A4%BE%E4%BA%A4%E5%85%83%E5%AE%87%E5%AE%99/cn.soulapp.android)）

**Comment by KieronQuinn** [comment]
Not a DarQ issue.
