### ISSUE TITLE
Add hide icon option [Feature Request]

### ISSUE THREAD

**Issue by MohamadBayz** [KieronQuinn/DarQ#68]
Hi having an option for hiding the launcher it's necessary for some user especially that now we can bypass hiding icon from Android Q 10 and also enter module setting inside Lsposed Manager itself as a organized person i prefer having all my modules inside lsposed and be able to configure them there too the icon in the launcher isn't necessary because once you configured the module you don't need to open the module as a daily basis like other app so i hope you consider adding it

**Comment by KieronQuinn** [comment]
I suggest using a custom launcher for this or disabling the component manually, it's not worth the time to implement a UI for enabling/disabling it and a recovery method for those who disable it with no other entry point.
