### ISSUE TITLE
Snapchat Dark Mode Not Working Properly 

### ISSUE THREAD

**Issue by StormySky16** [KieronQuinn/DarQ#70]
I am using the Xposed module, and for whatever reason Snapchat works on boot (i.e right after a restart), but after closing the app once after boot it will no longer start in dark mode. Any idea as to why this is?

**Comment by KieronQuinn** [comment]
Yes, they keep adding things to bypass it and it's not possible to fix anymore I don't think. Wait for official dark mode.
