### ISSUE TITLE
欢律app强制深色没有效果，求助

### ISSUE THREAD

**Issue by niu164** [KieronQuinn/DarQ#71]
如题
![Screenshot_2022-10-01-02-13-02-851_com.android.shell.jpg](https://user-images.githubusercontent.com/76257039/193331827-8829bc45-e1b5-40b4-a6ca-b806b4625421.jpg)
同样的设置，小黑盒能强制深色，欢律就不行
![Screenshot_2022-10-01-02-12-53-137_com.heytap.headset.jpg](https://user-images.githubusercontent.com/76257039/193331934-e8acfbab-796b-4c0b-a53a-d56b73cbbb1b.jpg)
![Screenshot_2022-10-01-02-12-47-871_com.max.xiaoheihe.jpg](https://user-images.githubusercontent.com/76257039/193331956-f73f7e2c-f335-4f27-81ce-4d572b9fe6eb.jpg)
😭😭

**Comment by KieronQuinn** [comment]
Not a DarQ issue.
