### ISSUE TITLE
Possible blacklist?

### ISSUE THREAD

**Issue by PeterKW** [KieronQuinn/DarQ#72]
Firstly, this looks really useful. Thank you very much for making it. 

Mostly I like all my applications to be in dark mode including applications I will install in the future. Therefore, I enabled 'Always use forced dark' in Advanced. My launcher application, Action Launcher, doesn't look as good in Forced Dark Mode. Is it possible to have all applications forced dark but with a customizable list of applications to disable forced dark in? 
Thank you very much,
P

**Comment by KieronQuinn** [comment]
#10
