### ISSUE TITLE
Difficulty stopping 'Fake Standby' colour inverting 

### ISSUE THREAD

**Issue by PeterKW** [KieronQuinn/DarQ#73]
Firstly this service is extremely useful to me so thank you very much for making it!

The thing I was trying to get working with this I would understand if there's no solution to it but there just might be something clever I should try before giving up.

https://www.f-droid.org/en/packages/android.jonas.fakestandby/ 

“FakeStandby is an Android app to turn off your screen while keeping apps running. This includes foreground jobs,”

So basically what it does is overlays an blank black screen over whatever application is ruining to mimic standby. In it's application it has a screen Inverter option that overlays white instead of black blank screen. But Android's 'clever' force dark sets both modes as a white black screen. I think that I can't set an ignore setting 'Force Dark' on this application because it's doing an overlay over other applications rather than opening it's own interface? I'm not sure if there's a way of detecting that it's active and then shutting off force dark? 

I hope I've managed to make what I've worked out so far make sense? Any suggestions on what I could try testing next to see if I can get it to work?

![Screenshot_20221030-001810.png](https://user-images.githubusercontent.com/13779157/198855957-e304e68b-017c-479f-9cea-8ebe4d793f7f.png)

![Screenshot_20221030-001940.png](https://user-images.githubusercontent.com/13779157/198855996-50ff5f29-3b70-4e3c-8b83-a305be3a1b85.png)

**Comment by PeterKW** [comment]
Referenced to: https://github.com/JonasBernard/FakeStandby

**Comment by KieronQuinn** [comment]
You are correct in that this is how it's implemented in Android, it's not something for me to fix in DarQ. The developer should use `setForceDarkAllowed` to prevent force dark from being applied to the view, which should also "fix" it in DarQ since it's the same feature.
