### ISSUE TITLE
[FEATURE] Opt-out an app

### ISSUE THREAD

**Issue by oreillygshane** [KieronQuinn/DarQ#74]
I love DarQ, it's a great service.

I blanket apply it to all apps, but FlightRadar24 looks bad (maps are dark).

Would it be possible to add a feature, to exclude certain apps from DarQ, when 'Always User Force Dark' is enabled?

Another workaround, would be to have a 'Select All' button in the 'Select Apps' section, so I could unselect chosen apps

**Comment by KieronQuinn** [comment]
#10
