### ISSUE TITLE
Request: Whitelist while in "Always use Force Dark"

### ISSUE THREAD

**Issue by VioletStorm** [KieronQuinn/DarQ#76]
When the Always use Force Dark toggle is enabled, allow the app list to be used to whitelist specific apps from having the DarQ effect applied

**Comment by KieronQuinn** [comment]
#10

**Comment by VioletStorm** [comment]
> #10 

You locked the other one though saying you would never do it. I say you should because people want it to happen, just move it to advanced options and let people know what issues it might have!

I don't see why no one should be allowed to have it just because it might not work well enough in some use cases
