### ISSUE TITLE
 In the program.TIM，The QQ group folder is completely black and does not display the file name.

### ISSUE THREAD

**Issue by WZL203** [KieronQuinn/DarQ#78]
In the program.TIM，The QQ group folder is completely black and does not display the file name.Can't see the file name.
![Screenshot_20230306-124731](https://user-images.githubusercontent.com/103476854/223021639-f7cc1ccd-4ddd-4d79-8b1c-b883753bda20.png)

**Comment by KieronQuinn** [comment]
Not a DarQ issue.

**Comment by JadeVane** [comment]
请问找到解决办法了吗，因为这个问题只能暂停应用到tim了
Did you find a solution to this problem? I had to suspend the use of tim because of this problem.
