### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by MulverineX** [KieronQuinn/DarQ#8]
On a Google Pixel 1st gen that's updated to Android 10, have tried several apps with the script ran with no success

**Comment by KieronQuinn** [comment]
Which apps?

**Comment by tmthecoder** [comment]
For myself, Snapchat does not show a dark theme with the force dark enabled. Am I doing anything wrong? Other apps do work

**Comment by KieronQuinn** [comment]
> For myself, Snapchat does not show a dark theme with the force dark enabled. Am I doing anything wrong? Other apps do work

Snapchat no longer works with force dark, they disabled.

**Comment by KieronQuinn** [comment]
As this hasn't had a response for nearly two months now, I'm closing this issue.
