### ISSUE TITLE
Strava doesnt go Dark Mode on Samsung S23

### ISSUE THREAD

**Issue by smartyn13r** [KieronQuinn/DarQ#82]
Strava doesn't go Dark Mode on Samsung S23 whereas on OnePlus7 the inbuild darkmode doe it well, can you please fix it.

**Comment by KieronQuinn** [comment]
Not a DarQ issue.

**Comment by smartyn13r** [comment]
Sad but fair.
We are already pushing Strava Dev Team to add dark mode support.
Thanks for building this app though
