### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by kittenvr** [KieronQuinn/DarQ#84]
Doesnt work with Snapchat

**Comment by KieronQuinn** [comment]
#70 

Official dark mode has now been released. Use that.

**Comment by kittenvr** [comment]
> 

how do i use it?

> #70
> 
> Official dark mode has now been released. Use that.

**Comment by KieronQuinn** [comment]
https://help.snapchat.com/hc/en-gb/articles/7012391907220-How-to-Enable-Dark-Mode-on-Snapchat

**Comment by kittenvr** [comment]
> https://help.snapchat.com/hc/en-gb/articles/7012391907220-How-to-Enable-Dark-Mode-on-Snapchat

is it snaqptchat pl;us?

**Comment by KieronQuinn** [comment]
> > https://help.snapchat.com/hc/en-gb/articles/7012391907220-How-to-Enable-Dark-Mode-on-Snapchat
> 
> is it snaqptchat pl;us?

No, this became a regular feature [last week](https://techcrunch.com/2023/08/08/snapchat-no-longer-requires-android-users-snapchat-subscription-enable-dark-mode/).
