### ISSUE TITLE
Use Shizuku Manager instead of adb

### ISSUE THREAD

**Issue by MacgyverJohnson** [KieronQuinn/DarQ#9]
Hello there @KieronQuinn .
Firstly I would like to express my gratitude for making such an amazing app for free, I hope u and ur family is doing fine among such an pandemic .
I would like to know whether it is possible to implement it using shizuku manager?
[https://shizuku.rikka.app/guide/](https://shizuku.rikka.app/guide/) Using Shizuku Manager it is possible to disable apps, disable activities, permissions and lots of other stuff....
Some apps that have used Shizuku manager

1. [Ice Box](https://play.google.com/store/apps/details?id=com.catchingnow.icebox&hl=en)
2. [App Ops](https://play.google.com/store/apps/details?id=rikka.appops&hl=en)
3. [Blocker](https://play.google.com/store/apps/details?id=com.merxury.blocker&hl=en)

Best Regards...

**Comment by KieronQuinn** [comment]
DarQ already uses librootjava, which has a very similar goal and is from a far more trustworthy developer. I don't see any benefits of using Shizuku manager over librootjava at all:

- They both use app_context via either ADB or a root shell to launch the code
- They both use binders to attach to the process for communication
- They both have the aim of accessing system components in standard Java code

I am grateful that you've brought the alternative to my attention though, as I may use it in future projects if librootjava stops working or is deprecated. In the meantime though, I'll stick to what I know.
